apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-reader-deployment
spec:
  selector:
    matchLabels:
      app: file-reader
  template:
    metadata:
      labels:
        app: file-reader
    spec:
      containers:
      - name: file-reader
        image: asia.gcr.io/medicbot-d925b/file-reader
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "160Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: file-reader-service
spec:
  type: LoadBalancer
  selector:
    app: file-reader
  ports:
  - port: 3000
    targetPort: 3000
